### ISSUE TITLE
BUG: r_fx_geometry is misaligned with lowered viewsize

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#641] opened 2022-03-14 10:02 UTC
**ezQuake version:**
3.6 alpha 10

**OS/device including version:**
RTX3070 GLSL renderer

**Describe the bug**
When you reduce viewsize below 100 the lines from r_fx_geometry are not displayed at the edge of objects like normal, but instead are a misaligned wireframe

**To Reproduce**
1. enable r_fx_geometry
2. Reduce viewsize
3. observe that the outline lines are no longer aligned with textures

**Expected behavior**
Lines adjust with changes to viewsize

**Screenshots**
Also please attach your config (.cfg) file

**Additional context**
I would say this is a low priority issue as it is unlikely players would reduce viewsize these days

**Comment by meag** [comment] 2022-04-02 19:19
Closing, duplicate of #598

**Closed by meag** 2022-04-02 19:19 UTC
