### ISSUE TITLE
BUG: standard renderer throws glsl compilation errors

### ISSUE THREAD

**Issue by ciscon** [ezQuake/ezquake-source#569] opened 2021-07-26 04:34 UTC
switching to std renderer gets:

*repeated error*

0:32(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
Shader->Compile(8B31) failed
0:31(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
Shader->Compile(8B31) failed
0:32(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
Shader->Compile(8B31) failed
0:32(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
]map dm1
VM_Load: "qwprogs"
Place of Two Deaths
== Cheats are enabled ==
Error: Unable to create lightmap texture array: error 1281
Error: Unable to create lightmap texture array: error 1281
Shutting down SDL audio.

*crash*

on separate std/glsl builds, the std build still appears to work fine other than those shader compilation errors still appearing, though bgnr is using the combined build but doesn't have the crash when playing a demo yet doesn't see players.

**Comment by ticketjp** [comment] 2021-07-26 04:42
Hi
I had same issue + invisible player model/skin when watching demos (didnt joined a server) and i noticed a big penalty in timedemo performance (3x more to complete)  to a earlier build from just some weaks ago.
Tested in linux, in 2 diff setups, one with a nvidia gfx on nouveau driver and another on intel igpu, with freshly compiled binaries in both setups, on vanilla ezquake, but using personal cfg.
I can append cfg if needed.
Thanks for attention

**Comment by ciscon** [comment] 2021-07-26 18:21
still getting those shader errors when switching to standard

**Comment by meag** [comment] 2021-07-27 05:29
Hi ciscon

I could reproduce (other) program compilation errors on AMD drivers by fixing the len=0 check (https://github.com/ezQuake/ezquake-source/commit/df5b1a9912ddc6dd634266d1b980ef71a6bc9969)

If you could try again and confirm if still broken?  Can't reproduce exactly what you've got, linux machine here can't run modern but will try and get something up and running.  Can you confirm if it happens starting up in classic, or if using classic-only build?

Thanks,
meag

**Comment by ciscon** [comment] 2021-07-27 05:34
just did a pull and recompile, still getting the error even when starting up with vid_renderer 0

--------------------------------

ezQuake &c1e13.6-dev-alpha9-dev&r r7109~956ceae4

<1d><1e><1e><1e><1e> &c1e1ezQuake Initialized&r <1e><1e><1e><1e><1f>


Type /help to access the manual.
Use /describe for help on commands.

execing /home/ciscon/games/quake/qw/autoexec.cfg
]map ultrav
couldn't exec server.cfg
VM_Load: "qwprogs"
&cf00Warning&r: weapon scripts will be executed client-side
&cf00Warning&r: high-lag teleport fix not available

<02>UltraViolence
== Cheats are enabled ==
ciscon entered the game
You got armor
Shader->Compile(8B31) failed
0:29(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
Shader->Compile(8B31) failed
0:30(9): error: syntax error, unexpected NEW_IDENTIFIER
...

**Comment by meag** [comment] 2021-07-28 03:02
Hi ciscon

Can you try that with `developer 1` set before starting the map?  Should hopefully tell us which program is failing.  Will update debugging messages if that doesn't help...

Thanks,

**Comment by ciscon** [comment] 2021-07-28 03:08
here's where it starts:

Compiling: aliasmodel-std[16]
Shader->Compile(8B31) failed
0:29(9): error: syntax error, unexpected NEW_IDENTIFIER
VertexShader.Compile() failed
Compiling: aliasmodel-std[17]
Shader->Compile(8B31) failed
0:30(9): error: syntax error, unexpected NEW_IDENTIFIER

attached is the full log.

[ezqoutput.txt](https://github.com/ezQuake/ezquake-source/files/6889993/ezqoutput.txt)

**Comment by meag** [comment] 2021-07-28 04:16
Thanks ciscon - that helps :)

**Comment by ciscon** [comment] 2021-07-28 04:19
groovy ;)

**Comment by meag** [comment] 2021-07-28 04:20
Hopefully fixed now...

**Comment by ciscon** [comment] 2021-07-28 04:21
just tried it, looks good.

**Closed** 2021-07-28 04:22 UTC

**Comment by ticketjp** [comment] 2021-07-28 18:03
Solved here too
Thanks for the work
