### ISSUE TITLE
BUG: viewsize/fov

### ISSUE THREAD

**Issue by kl00d** [ezQuake/ezquake-source#93] opened 2016-06-08 19:13 UTC
When using a viewsize under 100 the fov doesn't calculate properly, it seems the fov is higher

**Comment by meag** [comment] 2016-06-09 17:02
Hi there

Have looked into this, and it's due to the status bar being a fixed size, so as viewsize is reduced and the status bar is shown, the aspect ratio of the screen is effectively changed.  The effect is magnified the larger /vid_conscale you use, as 24 pixels (scaled) becomes a larger part of your vertical console resolution.

On my system, running at 1920 x 1080, vid_conscale 1:
- Viewsize 120 = 1920x1080 (ratio 1.778)
- Viewsize 110 = 1920x1056 (ratio 1.818)
- Viewsize 100 = 1920x1032 (ratio 1.86)
- Viewsize 90 = 1728x972 (ratio 1.778)
- Viewsize 80 = 1536x864 (ratio 1.778)

vid_conscale 2:

- Viewsize 120 = 960x540 (ratio 1.778)
- Viewsize 110 = 960x516 (ratio 1.86)
- Viewsize 100 = 960x492 (ratio 1.951)
- Viewsize 90 = 864x486 (ratio 1.778)
- Viewsize 80 = 768x432 (ratio 1.778)

vid_conscale 3:

- Viewsize 120 = 640x360 (ratio 1.778)
- Viewsize 110 = 640x336 (ratio 1.905)
- Viewsize 100 = 640x312 (ratio 2.051)
- Viewsize 90 = 576x312 (ratio 1.846)      (still 312 as we force the status bar to fit)
- Viewsize 80 = 512x288 (ratio 1.778)

Am thinking through solutions.  Ideally the viewsize would be a percentage of the total screen space, and so viewsize 100 would be fullscreen instead of 120, and 80 would be 80% horizontally and vertically, there would be black space at the sides and bottom, but the status bar at the bottom, if that makes sense.

Hmmm.  All suggestions welcome...

**Comment by meag** [comment] 2016-06-10 14:35
This is the kind of thing I was suggesting, keeping the aspect ratio constant by introducing black borders at the sides.  The left hand side is the new hud (simple % of width & height based on viewsize), the right hand side the old hud with /cl_sbar 1 (with viewsize 100 and 110 being a special case as the status bar appears).

![ezquake viewsize changes - newhud](https://cloud.githubusercontent.com/assets/10936291/15967758/dc4b0e88-2f20-11e6-8554-e1a51cda5b53.png)

**Comment by meag** [comment] 2016-06-15 19:33
This should be resolved by https://github.com/ezQuake/ezquake-source/commit/634b54c8316eede324f6df2fe990f957e4c1cff9

If you reduce viewsize now you should see the same cropping as per 2.2, keeping the aspect ratio correct.  Alternatively, you can set /scr_fovmode 1, introducing horizontal letterboxing as per screenshots above.

I'll leave open for a few days - please test the next nightly build and let us know what you think.

**Comment by kl00d** [comment] 2016-06-17 18:44
the fov seems lower now, but not the exact feel as ez 2.2

**Comment by meag** [comment] 2016-06-17 19:00
Are you on a 16:9 monitor/resolution?  ezQuake 2.2 was hard-coded to a 16:10 ratio, so there will be a slight difference.

**Comment by kl00d** [comment] 2016-06-17 20:22
yes 16:9 1920/1080 res

**Comment by meag** [comment] 2016-06-17 21:34
Ok, have tried to add a bit more info to the /fov changes [here](https://github.com/ezQuake/ezquake-source/wiki/Common-Issues) - very hastily written, but can you maybe have a read through and see if that gets you closer to what you're expecting?

On testing, I found that it's very easy in 2.2 to have vid_wideaspect be applied twice, which might be the cause of even more confusion.

**Comment by meag** [comment] 2016-06-24 19:58
Closing - please re-open if you believe there's an outstanding issue.

**Closed by meag** 2016-06-24 19:58 UTC
Labels: Renderer
