### ISSUE TITLE
os x: mouse cursor stays visible

### ISSUE THREAD

**Issue by freder** [ezQuake/ezquake-source#32] opened 2014-12-26 19:49 UTC
hi,

I compiled ezquake from source, which runs fine — except the mouse cursor doesn't disappear in the game. the menu looks fine, though.

unrelatedly, I used to use the version of ezquake that comes with [nQuake](http://nquake.com/), but the latest one doesn't work in os x yosemite. that one – IIRC – comes as an `*.app` that let's you change settings (like resolution, etc.) before you launch the actual game. — is that nQuake-specific or is there also a way to make an `*.app` when compiling ezquake from source? (I couldn't find any information on this).

**Comment by jite** [comment] 2015-01-01 21:17
While I think the problem is within the SDL2 library in combination with Apple, there are a couple of things you can try. First try to set vid_width 0 and vid_height 0 to force SDL to use the desktop resolution for ingame. If that doesn't help or it's already what you have, then set vid_width/vid_height to the appropriate values (your res) and see if that helps.

If neither of these help, not that I think this will either, but feel free to try and remove line 154 in vid_sdl2.c (SDL_SetCursor(NULL)).

**Comment by jite** [comment] 2015-02-12 13:08
Are you still experiencing this with latest master? I can't reproduce it

**Comment by freder** [comment] 2015-02-13 08:42
I just pulled and recompiled, but I still see the mouse cursor.
however: when I switch to another application and then go back into the game, it's gone.

**Comment by jite** [comment] 2015-03-01 15:26
Okey. Unfortunately I have no luck trying to reproduce this on my gf's iMac (OSX 10.10) :C What versions of OSX do you run? Gfx cards? Anyone of you think you could try to investigate more (code wise) what might be causing the behaviour? Thanks

**Comment by freder** [comment] 2015-03-02 09:59
![screen shot 2015-03-02 at 10 52 20](https://cloud.githubusercontent.com/assets/724844/6438605/21004e46-c0cb-11e4-98d0-c2b8ea45f88b.png)

**Comment by jite** [comment] 2015-03-02 10:20
Thanks @freder . Do you use multiple displays or just the iMac?

**Comment by fzwoch** [comment] 2015-03-02 10:28
![screen shot 2015-03-02 at 11 22 31](https://cloud.githubusercontent.com/assets/439605/6439006/c1a4b64a-c0ce-11e4-8ad3-d765f2e4ea1d.png)

For the record - happens here too. Using dual monitor setup. It looks like the cursor is reappearing without the SDL2 layer noticing. The API claims the cursor is still hidden.

Not sure if this is a SDL2 bug or some OS X quirk. We need to figure out what exactly is triggering this behaviour first.

For it is like this: Cursor is correctly hidden until I join a server or start a local game. Alt-Tab fixes it as mentioned before. in_restart does help as well.

**Comment by freder** [comment] 2015-03-02 10:29
@jite just the imac.

**Comment by jite** [comment] 2015-03-02 13:11
@freder @adonaldson Hi guys, you think you can fetch latest master and see if it works for you? (You will probably need to install the jansson library (brew install jansson). I added /qtv [gameserver:port] command to  join QTV from when playing or specifying server to watch through QTV, and /join supports joining from QTV)

**Comment by freder** [comment] 2015-03-02 14:06
@jite works for me, too.

**Comment by jite** [comment] 2015-03-02 14:28
Great, thanks a lot @freder, @fzwoch and @adonaldson ! Closing this issue.

**Closed by jite** 2015-03-02 14:28 UTC
