### ISSUE TITLE
BUG: Crashing after setting vid_displayfrequency

### ISSUE THREAD

**Issue by veRRoke** [ezQuake/ezquake-source#176] opened 2016-09-15 11:50 UTC
Ok everytime when im connecting to the server my vid_displayfrequency is on 0
When i do set it up to 120 manually i have to do vid_restart.
When i do this my ezquake always crashes and just goes to window in the end.

greetings veRRo

**Comment by jite** [comment] 2016-09-15 12:01
Please give us some more information than this:

What OS? What video card? What drivers? Which screen do you have? What resolution do you run in? Which version of ezQuake did you try?
"goes to window in the end", what do you mean? Is it a typo and you mean it exists and you end up in Windows, or does it set windowed mode of ezQuake and ezQuake still running?

We can't guess this kind of information and we need it to be able to help you :)

**Comment by meag** [comment] 2016-10-25 19:15
Going to close this as I believe it's a duplicate of https://github.com/ezQuake/ezquake-source/issues/120

Verro, I remember once we thought this was linked to textures, as you had removed all textures and that made it always happen, but with certain textures (perhaps on a certain map?) it didn't.  Is it possible you can package up the common textures and the textures being used for a map it is crashing on and upload everything in a .zip file somewhere?  Also what version of nvdia drivers you are using?  Lots of people seem to have this problem but as I can't always replicate I can't really work on it :(

Thanks,
meag

**Closed by meag** 2016-10-25 19:15 UTC
