### ISSUE TITLE
BUG: messages in between the games are shown in console, but not on the screen

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#175] opened 2016-09-11 15:56 UTC
Right after the game ends, and before the next map, if anybody says anything,
it is shown in console, but not on the screen.

**Comment by meag** [comment] 2016-09-11 16:30
During the intermission?  Notification area & hud elements are suppressed during the intermission, otherwise screenshots would be ruined.

**Comment by mmavova** [comment] 2016-09-11 16:51
I see, so it is a feature? :)

On 09/11/2016 12:30 PM, meag wrote:
> During the intermission? Notification area & hud
> elements are suppressed during the intermission,
> otherwise screenshots would be ruined.
>
> — You are receiving this because you authored the
> thread. Reply to this email directly, view it on GitHub
> <https://github.com/ezQuake/ezquake-source/issues/175#issuecomment-246189265>,
>
>
or mute the thread

**Comment by meag** [comment] 2016-10-25 16:27
It's 'by design', certainly.

I quite fancy having customisable hud for intermission, showing statistics etc, maybe it can be looked at then?

**Comment by jite** [comment] 2016-11-02 12:07
Yep exactly it's by design. Closing this, customisable hud for intermission sounds like a nice feature request @meag :)

**Closed by jite** 2016-11-02 12:07 UTC
