### ISSUE TITLE
BUG: /weapon does not set w_rank userinfo

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#140] opened 2016-08-14 14:52 UTC
Somebody reported to me the following bug:

alias +lg_rl "weapon 8 7 6 5 4 3 2 1;+attack"
alias -lg_rl "-attack"
bind +lg_rl mouse1

if you use this in a game you would expect to switch to rl once you run out of lg ammo,
but it never happens.

**Comment by meag** [comment] 2016-08-14 15:12
(think last line is `/bind mouse1 +lg_rl`)

Do you find that if you are holding down the fire button, it switches to SNG instead?  The server is doing the weapon switching in that case, and you can rank the weapons server-side via `/setinfo w_rank xyz`

Needs a recent KTX change (https://github.com/deurk/ktx/commit/def43af102493b567e5bd5e2953f523379c04c6e)

**Comment by mmavova** [comment] 2016-08-14 16:43
yes, we saw it switch to SNG.

So are you saying this is not a bug?

The server admin changed w_rank and the script started working.

**Comment by meag** [comment] 2016-08-14 18:45
The server admin shouldn't have to change w_rank, it's per-client, so you can specify it at the console (or in a script) and any new version of ktx should obey.

"not a bug"... well, /weapon is client-side, but when running out of ammo, picking a new weapon is done server-side.  Certainly it is how it is designed, but personally I don't like it and would prefer to see all weapon-switching moved server-side.

I'll leave this open, we should add an option to send "weapon x y z" to the server via w_rank, so running out of ammo behaves as expected.

**Comment by meag** [comment] 2020-10-03 12:47
Closing - the weapon-switching protocol extension should hopefully deal with these situations

**Closed** 2020-10-03 12:48 UTC
Labels: Input
