### ISSUE TITLE
BUG: QuakeServers.net source not working (OSX)

### ISSUE THREAD

**Issue by shmabler** [ezQuake/ezquake-source#212] opened 2017-04-04 23:18 UTC
The QuakeServers.net source is not working. It will never update. I'm running macOS version of ezQuake 3.0.1 dated July 2016.

I also thought that all the servers with master as the server type weren't working, but now they all say file and QuakeServers.net says URL type. So, I may be confused or something changed.

Could you please fix/check/update the server sources on the macOS version to make sure they are working?

Thank You.

**Comment by meag** [comment] 2017-04-05 10:20
Do you see any error messages in the console when trying to refresh from those sources?

Can you confirm that `./ezquake/sb/cache/` directory contains file: `https_3a_2f_2fwww.quakeservers.net_2flists_2fservers_2fglobal.txt`

(or similar, depending on which source was selected).  If so, can you confirm if the date modified changes when you refresh sources, and attach the file here?

**Comment by shmabler** [comment] 2017-04-05 19:10
I see no error messages in the console, however pressing the console button doesn't work from the server or source screens.

There is a file called "http_3a_2f_2fwww.quakeservers.net_2flists_2fservers_2fgl".

The date/time modified of the file changes if I select the source as active and press space to refresh.

I'm including the file here
[http_3a_2f_2fwww.quakeservers.net_2flists_2fservers_2fgl.txt](https://github.com/ezQuake/ezquake-source/files/900530/http_3a_2f_2fwww.quakeservers.net_2flists_2fservers_2fgl.txt)

Also, this one source is type URL and all the others are file. In the past I thought there were master, but now they aren't.

**Comment by meag** [comment] 2017-04-05 22:18
Can you confirm the full path to ezquake?  Looks like the filename is being truncated?

**Comment by shmabler** [comment] 2017-04-05 22:45
The file name is not the same as yours. I quoted exactly. I had to add ".txt" to the end to upload though.

The full path is: Partition/Applications/ezQuake.app/Contents/Resources/ezquake/sb/cachehttp_3a_2f_2fwww.quakeservers.net_2flists_2fservers_2fgl

**Comment by meag** [comment] 2017-04-06 06:55
The file name is in a particular format, corresponding to the URL.  The format produced on your computer indicates a URL (http://www.quakeservers.net/lists/servers/gl) which would redirect you to the home page, whereas adding `obal.txt` gives the valid address.

The full path you've just given is 127 characters long, which corresponds to the maximum filename length for 3.0.1 (discussed here https://github.com/ezQuake/ezquake-source/issues/141), so I'd say that's the root cause of the issue.

**Comment by shmabler** [comment] 2017-04-06 19:12
Meag, what can I do? Also, can the maximum path length be increased? I tried renaming ezQuake to just "Q" and put it in my root directory to cut down on the path length, but that didn't work.

**Comment by meag** [comment] 2017-04-06 21:22
The path length has been increased in more recent versions, so will be fixed in 3.1 when it is released.

To get this at the moment you should follow the instructions [here](https://github.com/ezQuake/ezquake-source/blob/master/COMPILING_ON_OSX.txt) to compile a nightly version.

**Comment by meag** [comment] 2018-04-12 22:25
Closing: this should be fixed by https://github.com/ezQuake/ezquake-source/pull/249

**Closed by meag** 2018-04-12 22:25 UTC
