### ISSUE TITLE
BUG: ezquake resets values of some cvars after connect

### ISSUE THREAD

**Issue by petska** [ezQuake/ezquake-source#188] opened 2017-01-08 02:53 UTC
ezquake resets values of some cvars when I connect to some server. For example: hud_bar_armor_pos_x, gl_gammacorrection and some others.
This issue was at ezquake v2 & still exist at ezquake latest nightly build 2017-01-07-ec7f207.

**Comment by meag** [comment] 2017-01-08 10:16
Maybe this is being caused by an f_spawn trigger?  `/aliasedit f_spawn` to see what is being executed.
Is it one server in particular (perhaps with a gamedir set) or all servers?

**Comment by petska** [comment] 2017-01-08 11:41
`f_spawn` is empty. any server.

**Comment by meag** [comment] 2017-01-08 11:52
Okay, let's go with tracking down `/gl_gammacorrection`... what is it set to before and after?  Does it happen every time?  Are these standard connections to servers, or does it happen with qtv / watching demos as well?

**Comment by petska** [comment] 2017-01-08 12:22
`gl_gammacorrection` is 1 at ezquake\configs\config.cfg
when I start ezquake and type `gl_gammacorrection` <ENTER> I got:
`default value is "0"
current value is "0"
latched value is "1"`

When I connect any server (local also) I have value "0" until I `vid_restart`

**Comment by meag** [comment] 2017-01-31 20:35
Hi there

Latched values do required a vid_restart, so that would be correct behaviour.  How is ezquake/configs/config.cfg being executed?  /cfg_load?  Are you using nquake .pk3 files?

Are you saying that *after* /vid_restart, you connect to another server and it goes back to 0?

hud_bar_armor_pos_x isn't a latch cvar so this might be two different issues.

**Comment by meag** [comment] 2017-02-28 12:03
mvd_autohud ?

**Comment by meag** [comment] 2017-03-14 18:49
Can you check if you have an /on_enter alias?  KTX will execute this unless you set kf to 32 (`/setinfo kf 32`)

**Comment by meag** [comment] 2017-03-23 22:42
Closing: believe this to be a config error.

**Closed by meag** 2017-03-23 22:42 UTC
