### ISSUE TITLE
BUG: folder bugs (servers.txt)

### ISSUE THREAD

**Issue by niclaslindstedt** [ezQuake/ezquake-source#42] opened 2015-06-21 12:27 UTC
In my QuakeWorld folder, these weird folders keep popping up:

ezq/
ezquak/
se/
servers.t/
servers.txt/

I can't reproduce it, though if I remove the folders they will reappear after a while at seemingly random times.

**Comment by neogeographica** [comment] 2015-09-25 03:39
Question that occurred to me while looking at this: is the `va` utility function is used from multiple different threads? `va` is often used to compose strings to do file activities and create directories, and it doesn't look like that function is threadsafe on a multicore system. Unless the compiler is for-sure translating `idx++` into a single fetch-and-add instruction.

But I think to make sure the atomic increment happens, you'd want to use a gcc atomic-op builtin and tell the compile to specifically target a pentium (or later) architecture, cf. http://stackoverflow.com/questions/2353371/how-to-do-an-atomic-increment-and-fetch-in-c . Or perhaps do some platform-specific synchronization stuff with the various threading libraries, and put that code in the sys_*.c file, but the gcc builtin seems nicer if it works.

**Comment by JoakimSoderberg** [comment] 2015-09-25 09:23
Using a compiler specific feature is never the way to go with a multiplatform piece of software. Especially when the idea is to use a **gcc** specific feature and most people play the game on **windows**

You are completely correct in the fact that `va` isn't thread safe. It has never been, since Quake from the start has never been multithreaded. Any code that that is now multi-threaded and uses anything connected to `va` should be rewritten. Either that or simply getting rid of all uses of these non threadsafe functions (huge work, not likely to happen).

However... Your proposed solution in that stackoverflow issue is not relevant anyway. `va` uses a static buffer for strings. So the next call to `va` will overwrite this entire string. If multiple threads are doing that, there would be a lot more chaos than this :)

If the issue is thread realted I doubt it has anything to do with `va`. But rather with something thread related in here: https://github.com/ezQuake/ezquake-source/blob/master/EX_browser_net.c

**Comment by neogeographica** [comment] 2015-09-25 14:18
`va` uses a rotating pool of 32 buffers yeah? There are functions like Log_AutoLogging_SaveMatch that do multiple calls to `va` and treat the returned pointers as usable together over the scope of the function... which they are, in a single-threaded situation, as long as you are using less than 32 of them.

A multithreaded situation *could* get you into trouble if it causes more than 32 simultaneous uses of `va`, but at a glance there don't seem to be that many threads flying around. If that's not the issue then a race between threads hitting `idx++` may be more likely.

If this is indeed a problem they can of course solve it however they like... the gcc builtin is just one way of making sure that the necessary asm is issued. gcc is crossplatform; admittedly the instruction is x86-specific but I don't know how much of a concern that is (do people care about building ezQuake for ARM?). If using gcc on Windows is not desirable then maybe use a Windows synchronization intrinsic and put it in sys_win.c or whatever.

**Comment by JoakimSoderberg** [comment] 2015-09-25 14:32
Yea, still... That's a bad way of solving it. Don't use compiler specific features. Period :) If it's a thread issue, normally a lock should be used. Sure I can think of people wanting to build it for ARM or MIPS. Say running it on an iPhone, or maybe Raspberry Pi. Simply don't do it...

IF the reason this error occurs is because of `va` (which is yet to be determined), the solution is probably not locking or trying to make calls to `va` atomic. It was not designed for multiple threads. Instead either `va` should not be used in that case (plenty of other options). Or `va` should be removed all together from the code.

But better to find the actual culprit before changing random things :)

**Comment by jite** [comment] 2015-09-25 20:18
@neogeographica It's very much appreciated that you help out! You are completely right that there are a lot of issues with thread safety in the code, or rather the lack of it. Com_Printf isn't exactly thead safe either but used from different threads unfortunately.

I have to agree that I don't think compiler specific fixes for different platforms might be the best solution (initially atleast). If there are portable/generic ways of solving a problem I do prefer them over compiler-/os-/hardware- (etc) specific solutions.

I haven't managed to reproduce this problem at all. Have you managed? If yes; have you tested with a thread safe va?

**Comment by jite** [comment] 2015-12-09 18:14
I've made some commits to remove the usage of va() in some files. In others I've currently just removed usage of it from filesystem operations, including operations on servers.txt. Would be interesting to know if it solved this particular issue.

**Comment by jite** [comment] 2016-01-22 13:34
Ping

**Comment by niclaslindstedt** [comment] 2016-01-22 13:47
Nice. Will check out if I get time.

**Comment by meag** [comment] 2016-07-01 07:20
Can I ask if this is still happening?  If not, am minded to close this for now and re-open if it happens again.

**Comment by meag** [comment] 2016-07-12 10:46
Closing for the moment, can re-open if it happens again.

**Closed by meag** 2016-07-12 10:46 UTC
