### ISSUE TITLE
ezQuake doesn't run on Ubuntu 20.04 and variants

### ISSUE THREAD

**Issue by fabianod** [ezQuake/ezquake-source#420] opened 2020-11-07 21:16 UTC
ezQuake's newest version (Linux (64-bit) 3.2.2 22nd September 2020) and also the version that comes with nQuake, doesn't run on three different machines running (Ubuntu 20.04.1 LTS)

1. First machine a AMD 8300 16GB with no discrete graphics card
2. Second machine a Intel Core i5 3210M 8GB with no discrete graphics card
3. Third machine a AMD Ryzen 3600 16GB with a GTX 1660TI graphics card

This process was done in a new and clean installation of nQuake for Linux:

cd \nquake
./ezquake-linux-x86_64
./ezquake-linux-x86_64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by meag** [comment] 2020-11-07 22:23
Thanks.

Is libpng installed on the machine?  I'll leave this to the linux gurus to answer fully (@ciscon ?) but while we provide executables for linux & osx/macos/whatever, the advice is generally to build yourself, as we don't link statically as we do for Windows executables.

There's a guide [here](https://github.com/ezQuake/ezquake-source/blob/master/COMPILING_ON_LINUX.txt) which I used today and worked fine on Ubuntu 20, and also a `build-linux.sh` script in the source folder which should in theory do everything for you.

Thanks,
meag

**Comment by meag** [comment] 2020-11-07 22:32
Sorry, might have missed the point of your post a bit there: I think you'd either have to `apt-get install libpng-dev`, or really the answer is for us to upgrade to libpng16?

**Comment by meag** [comment] 2020-11-07 22:52
Going to close this - the builds are on Ubuntu 20 now (the travis image was updated) so we should be linking to libpng 1.6 now - this should go away with newer builds.

**Closed by meag** 2020-11-07 22:52 UTC

**Comment by fabianod** [comment] 2020-11-08 02:09
Thanks! I tried every tutorial I found online to solve this problem, but looks like it won't work with Ubuntu 20.04, cause of some change in the location of some files inside the .deb.

**Comment by meag** [comment] 2020-11-10 12:03
Hi @fabianod 

Your rendering problem you've reported on quakeworld.nu is probably just with 3.6 rather than 3.2, you can checkout & build 3.2 (which I think this ticket was asking for) by switching to the ezquake_32 branch then `make clean && make -j5` etc

For 3.6 rendering - can you please check out the last post on https://github.com/ezQuake/ezquake-source/issues/416, and maybe try the `-r-trace` thing yourself & upload logs?  It sounds similar but different.

Also can you upload your crosshair image, as it seems to be interlaced and I think we can get rid of that libpng warning.

Thanks,

**Comment by rozhok** [comment] 2021-01-26 12:55
I can confirm it's still the case for Linux Mint 20.1 and compiled binaries.

I've had to build executable on my own and was solved the issue.

**Comment by ata-star** [comment] 2021-02-12 07:17
hey, im using
Ubuntu 20.04.2 LTS x86_64 
and it says 
./ezquake-linux-x86_64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by meag** [comment] 2021-02-12 07:22
@ata-star is that from an executable you built, or one you downloaded?  If downloaded, where from and what version?

**Comment by ata-star** [comment] 2021-02-12 23:31
http://www.ezquake.com/ 
 Linux (64-bit) 3.2.3 9th February 2021 Full

**Comment by lu-ccc** [comment] 2021-02-14 07:04
same problem same version
Ubuntu 20.04

**Comment by fzwoch** [comment] 2021-02-14 09:21
It is probably due to the `ezquake_32` branch still builds on Travis's `trusty` image and not `focal` as master does. So 3.2.x versions will still link to older libpng versions.

**Comment by henriquedesousa** [comment] 2021-02-26 23:57
Finally I managed to compile ezQuake on Linux Mint 20 (Ubuntu 20.04 based) !

I was also having the `libpng12.so.0: cannot open` so I tried to compile but ran into many issues.

1- libpng12 is not supported anymore on Ubuntu 20. Solution: compile and install using [this guide](https://askubuntu.com/a/966854/215112). And give some karma to the user on SO.
2- snd_mem.c:27:10: fatal error: sndfile.h: No such file or directory
Fixed by following @meag guide linked above on this page, namely the flag `OLD_WAV_LOADING=1 make -j5`

It now compiles just fine. MTIA from an UT99 fan :D

**Comment by ciscon** [comment] 2021-02-27 00:00
the build-linux.sh script mentioned above installs all of the dependencies for you before it compiles, fyi.

**Comment by henriquedesousa** [comment] 2021-02-27 00:20
That script does not install libpng12 because it was removed in Ubuntu 20 in favour of libpng16.

**Comment by ciscon** [comment] 2021-02-27 00:20
you don't need libpng12 if you're compiling it yourself

**Comment by henriquedesousa** [comment] 2021-02-27 00:23
Indeed, just tried it again and it compiled against libpng16. I was confused by the message `error while loading shared libraries: libpng12.so.0`. Cheers
